// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: src/proto/backdoor-service.proto

package backdoor

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BackdoorService_RemoteExec_FullMethodName = "/backdoor.BackdoorService/RemoteExec"
)

// BackdoorServiceClient is the client API for BackdoorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BackdoorServiceClient interface {
	RemoteExec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Out, Out], error)
}

type backdoorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBackdoorServiceClient(cc grpc.ClientConnInterface) BackdoorServiceClient {
	return &backdoorServiceClient{cc}
}

func (c *backdoorServiceClient) RemoteExec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Out, Out], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BackdoorService_ServiceDesc.Streams[0], BackdoorService_RemoteExec_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Out, Out]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BackdoorService_RemoteExecClient = grpc.BidiStreamingClient[Out, Out]

// BackdoorServiceServer is the server API for BackdoorService service.
// All implementations must embed UnimplementedBackdoorServiceServer
// for forward compatibility.
type BackdoorServiceServer interface {
	RemoteExec(grpc.BidiStreamingServer[Out, Out]) error
	mustEmbedUnimplementedBackdoorServiceServer()
}

// UnimplementedBackdoorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBackdoorServiceServer struct{}

func (UnimplementedBackdoorServiceServer) RemoteExec(grpc.BidiStreamingServer[Out, Out]) error {
	return status.Errorf(codes.Unimplemented, "method RemoteExec not implemented")
}
func (UnimplementedBackdoorServiceServer) mustEmbedUnimplementedBackdoorServiceServer() {}
func (UnimplementedBackdoorServiceServer) testEmbeddedByValue()                         {}

// UnsafeBackdoorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackdoorServiceServer will
// result in compilation errors.
type UnsafeBackdoorServiceServer interface {
	mustEmbedUnimplementedBackdoorServiceServer()
}

func RegisterBackdoorServiceServer(s grpc.ServiceRegistrar, srv BackdoorServiceServer) {
	// If the following call pancis, it indicates UnimplementedBackdoorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BackdoorService_ServiceDesc, srv)
}

func _BackdoorService_RemoteExec_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BackdoorServiceServer).RemoteExec(&grpc.GenericServerStream[Out, Out]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BackdoorService_RemoteExecServer = grpc.BidiStreamingServer[Out, Out]

// BackdoorService_ServiceDesc is the grpc.ServiceDesc for BackdoorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BackdoorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "backdoor.BackdoorService",
	HandlerType: (*BackdoorServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RemoteExec",
			Handler:       _BackdoorService_RemoteExec_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "src/proto/backdoor-service.proto",
}
